spring:
  application:
    name: ITQGroup_side_api
server:
  port: 8089

api:
  documents:
    url: ${DOCUMENT_API_URL:http://localhost:8088}

document-batch-creation:
  file:
    path: src/main/resources/static/document-batch-creation-file.txt

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
  level:
    root: info