package com.ITQGroup.enums;

public enum ErrorResponseCode {

    NEGATIVE_FILE_QUANTITY("NEGATIVE_FILE_QUANTITY"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    QUANTITY_PARSING_ERROR("QUANTITY_PARSING_ERROR"),
    BAD_REQUEST("BAD_REQUEST"),
    NOT_FOUND("NOT_FOUND"),
    EMPTY_RESPONSE_BODY("EMPTY_RESPONSE_BODY");

    ErrorResponseCode(String name) {
    }
}
